name: test_and_lint

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm install --save-dev jest
      - run: node --experimental-vm-modules node_modules/jest/bin/jest.js
  lint:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: make lint
